[package]
name = "kordent-desktop"
description = "Desktop application for KORDENT ERP."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "kordent_desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
